# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_no', models.CharField(max_length=40, unique=True, verbose_name='订单号')),
                ('user_id', models.IntegerField(verbose_name='买家ID')),
                ('goods_money', models.DecimalField(decimal_places=2, default=9999999.0, max_digits=10, verbose_name='商品总金额')),
                ('express_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='快递费')),
                ('all_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('actual_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际支付金额')),
                ('status', models.IntegerField(default=0, verbose_name='订单状态 0等待付款/1交易已完成/2交易失效')),
                ('adress_id', models.IntegerField(verbose_name='订单地址,来源：用户地址表的ID')),
                ('exist_flag', models.IntegerField(default=0, verbose_name='订单是否被删除,0表示没有删除 1表示删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('close_time', models.DateTimeField(null=True, verbose_name='订单关闭时间')),
                ('remark', models.CharField(max_length=1000, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单明细ID')),
                ('order_id', models.IntegerField(verbose_name='订单id')),
                ('seller_id', models.IntegerField(verbose_name='卖家id')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('all_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
            ],
        ),
    ]
