# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-15 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_list',
            new_name='OrderList',
        ),
    ]
