# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190816_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注'),
        ),
    ]
