# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-15 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190815_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='list_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='订单明细ID'),
        ),
    ]
