# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190816_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('shopping_car_id', models.AutoField(primary_key=True, serialize=False, verbose_name='购物车ID')),
                ('user_id', models.IntegerField(verbose_name='买家ID')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('if_order', models.IntegerField(verbose_name='是否生成订单')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
            ],
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单id'),
        ),
    ]
