# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, verbose_name='颜色')),
                ('size', models.CharField(max_length=10, verbose_name='尺寸')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='ShopGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=100, verbose_name='商品标题')),
                ('goods_type', models.CharField(max_length=16, verbose_name='商品类型')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=10, verbose_name='证件类型')),
                ('card_num', models.CharField(max_length=32, verbose_name='证件号码')),
                ('pic', models.BinaryField(verbose_name='证件照片')),
                ('validity_date', models.DateField(verbose_name='证件有效期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(verbose_name='开店日期')),
                ('level', models.CharField(max_length=16, verbose_name='店铺等级')),
                ('address', models.CharField(max_length=254, verbose_name='店铺地址')),
                ('store_type', models.CharField(max_length=16, verbose_name='店铺分类')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('shopkeeper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.Shopkeeper')),
            ],
        ),
        migrations.AddField(
            model_name='shopgoods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Store'),
        ),
    ]
